name: Update Doxygen

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/workflows/boosttest.yml'
      - '.github/workflows/cmake-lint.yml'
      - 'README.md'
      - 'LICENSE'
      - 'tests/*'

jobs:
  doxygen:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: install_dependencies
      run: |
        sudo apt-get update -y && sudo apt-get install cmake libeigen3-dev libboost-all-dev doxygen graphviz -y
    - name: build_doxygen
      run: |
        mkdir -p /tmp/build && cd /tmp/build
        cmake $OLDPWD && make doc
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: /tmp/build/doc/html
        destination_dir: doxygen
